/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedReviewRouteImport } from './routes/_authenticated/review'
import { Route as AuthenticatedProgressRouteImport } from './routes/_authenticated/progress'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedExploreRouteImport } from './routes/_authenticated/explore'
import { Route as AuthenticatedExamRouteImport } from './routes/_authenticated/exam'
import { Route as AuthenticatedDiagnosticRouteImport } from './routes/_authenticated/diagnostic'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedTopicsIndexRouteImport } from './routes/_authenticated/topics.index'
import { Route as AuthenticatedToolsIndexRouteImport } from './routes/_authenticated/tools.index'
import { Route as AuthenticatedTheoryIndexRouteImport } from './routes/_authenticated/theory.index'
import { Route as AuthenticatedStudyIndexRouteImport } from './routes/_authenticated/study.index'
import { Route as AuthenticatedTopicsSlugRouteImport } from './routes/_authenticated/topics.$slug'
import { Route as AuthenticatedToolsFunctionsRouteImport } from './routes/_authenticated/tools.functions'
import { Route as AuthenticatedToolsCalculatorRouteImport } from './routes/_authenticated/tools.calculator'
import { Route as AuthenticatedTheorySlugRouteImport } from './routes/_authenticated/theory.$slug'
import { Route as AuthenticatedStudyIdRouteImport } from './routes/_authenticated/study.$id'
import { Route as AuthenticatedMaterialsIdRouteImport } from './routes/_authenticated/materials.$id'
import { Route as AuthenticatedAdminReportsRouteImport } from './routes/_authenticated/admin.reports'
import { Route as AuthenticatedAdminAnalyticsRouteImport } from './routes/_authenticated/admin.analytics'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedReviewRoute = AuthenticatedReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProgressRoute = AuthenticatedProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedExploreRoute = AuthenticatedExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedExamRoute = AuthenticatedExamRouteImport.update({
  id: '/exam',
  path: '/exam',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDiagnosticRoute = AuthenticatedDiagnosticRouteImport.update({
  id: '/diagnostic',
  path: '/diagnostic',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTopicsIndexRoute =
  AuthenticatedTopicsIndexRouteImport.update({
    id: '/topics/',
    path: '/topics/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedToolsIndexRoute = AuthenticatedToolsIndexRouteImport.update({
  id: '/tools/',
  path: '/tools/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTheoryIndexRoute =
  AuthenticatedTheoryIndexRouteImport.update({
    id: '/theory/',
    path: '/theory/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedStudyIndexRoute = AuthenticatedStudyIndexRouteImport.update({
  id: '/study/',
  path: '/study/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTopicsSlugRoute = AuthenticatedTopicsSlugRouteImport.update({
  id: '/topics/$slug',
  path: '/topics/$slug',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedToolsFunctionsRoute =
  AuthenticatedToolsFunctionsRouteImport.update({
    id: '/tools/functions',
    path: '/tools/functions',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedToolsCalculatorRoute =
  AuthenticatedToolsCalculatorRouteImport.update({
    id: '/tools/calculator',
    path: '/tools/calculator',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTheorySlugRoute = AuthenticatedTheorySlugRouteImport.update({
  id: '/theory/$slug',
  path: '/theory/$slug',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedStudyIdRoute = AuthenticatedStudyIdRouteImport.update({
  id: '/study/$id',
  path: '/study/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMaterialsIdRoute =
  AuthenticatedMaterialsIdRouteImport.update({
    id: '/materials/$id',
    path: '/materials/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminReportsRoute =
  AuthenticatedAdminReportsRouteImport.update({
    id: '/admin/reports',
    path: '/admin/reports',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminAnalyticsRoute =
  AuthenticatedAdminAnalyticsRouteImport.update({
    id: '/admin/analytics',
    path: '/admin/analytics',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/diagnostic': typeof AuthenticatedDiagnosticRoute
  '/exam': typeof AuthenticatedExamRoute
  '/explore': typeof AuthenticatedExploreRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/progress': typeof AuthenticatedProgressRoute
  '/review': typeof AuthenticatedReviewRoute
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/materials/$id': typeof AuthenticatedMaterialsIdRoute
  '/study/$id': typeof AuthenticatedStudyIdRoute
  '/theory/$slug': typeof AuthenticatedTheorySlugRoute
  '/tools/calculator': typeof AuthenticatedToolsCalculatorRoute
  '/tools/functions': typeof AuthenticatedToolsFunctionsRoute
  '/topics/$slug': typeof AuthenticatedTopicsSlugRoute
  '/study/': typeof AuthenticatedStudyIndexRoute
  '/theory/': typeof AuthenticatedTheoryIndexRoute
  '/tools/': typeof AuthenticatedToolsIndexRoute
  '/topics/': typeof AuthenticatedTopicsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/diagnostic': typeof AuthenticatedDiagnosticRoute
  '/exam': typeof AuthenticatedExamRoute
  '/explore': typeof AuthenticatedExploreRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/progress': typeof AuthenticatedProgressRoute
  '/review': typeof AuthenticatedReviewRoute
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/materials/$id': typeof AuthenticatedMaterialsIdRoute
  '/study/$id': typeof AuthenticatedStudyIdRoute
  '/theory/$slug': typeof AuthenticatedTheorySlugRoute
  '/tools/calculator': typeof AuthenticatedToolsCalculatorRoute
  '/tools/functions': typeof AuthenticatedToolsFunctionsRoute
  '/topics/$slug': typeof AuthenticatedTopicsSlugRoute
  '/study': typeof AuthenticatedStudyIndexRoute
  '/theory': typeof AuthenticatedTheoryIndexRoute
  '/tools': typeof AuthenticatedToolsIndexRoute
  '/topics': typeof AuthenticatedTopicsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/diagnostic': typeof AuthenticatedDiagnosticRoute
  '/_authenticated/exam': typeof AuthenticatedExamRoute
  '/_authenticated/explore': typeof AuthenticatedExploreRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/progress': typeof AuthenticatedProgressRoute
  '/_authenticated/review': typeof AuthenticatedReviewRoute
  '/_authenticated/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/_authenticated/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/_authenticated/materials/$id': typeof AuthenticatedMaterialsIdRoute
  '/_authenticated/study/$id': typeof AuthenticatedStudyIdRoute
  '/_authenticated/theory/$slug': typeof AuthenticatedTheorySlugRoute
  '/_authenticated/tools/calculator': typeof AuthenticatedToolsCalculatorRoute
  '/_authenticated/tools/functions': typeof AuthenticatedToolsFunctionsRoute
  '/_authenticated/topics/$slug': typeof AuthenticatedTopicsSlugRoute
  '/_authenticated/study/': typeof AuthenticatedStudyIndexRoute
  '/_authenticated/theory/': typeof AuthenticatedTheoryIndexRoute
  '/_authenticated/tools/': typeof AuthenticatedToolsIndexRoute
  '/_authenticated/topics/': typeof AuthenticatedTopicsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/dashboard'
    | '/diagnostic'
    | '/exam'
    | '/explore'
    | '/profile'
    | '/progress'
    | '/review'
    | '/admin/analytics'
    | '/admin/reports'
    | '/materials/$id'
    | '/study/$id'
    | '/theory/$slug'
    | '/tools/calculator'
    | '/tools/functions'
    | '/topics/$slug'
    | '/study/'
    | '/theory/'
    | '/tools/'
    | '/topics/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/dashboard'
    | '/diagnostic'
    | '/exam'
    | '/explore'
    | '/profile'
    | '/progress'
    | '/review'
    | '/admin/analytics'
    | '/admin/reports'
    | '/materials/$id'
    | '/study/$id'
    | '/theory/$slug'
    | '/tools/calculator'
    | '/tools/functions'
    | '/topics/$slug'
    | '/study'
    | '/theory'
    | '/tools'
    | '/topics'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/signup'
    | '/_authenticated/dashboard'
    | '/_authenticated/diagnostic'
    | '/_authenticated/exam'
    | '/_authenticated/explore'
    | '/_authenticated/profile'
    | '/_authenticated/progress'
    | '/_authenticated/review'
    | '/_authenticated/admin/analytics'
    | '/_authenticated/admin/reports'
    | '/_authenticated/materials/$id'
    | '/_authenticated/study/$id'
    | '/_authenticated/theory/$slug'
    | '/_authenticated/tools/calculator'
    | '/_authenticated/tools/functions'
    | '/_authenticated/topics/$slug'
    | '/_authenticated/study/'
    | '/_authenticated/theory/'
    | '/_authenticated/tools/'
    | '/_authenticated/topics/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/review': {
      id: '/_authenticated/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof AuthenticatedReviewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/progress': {
      id: '/_authenticated/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof AuthenticatedProgressRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/explore': {
      id: '/_authenticated/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof AuthenticatedExploreRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/exam': {
      id: '/_authenticated/exam'
      path: '/exam'
      fullPath: '/exam'
      preLoaderRoute: typeof AuthenticatedExamRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/diagnostic': {
      id: '/_authenticated/diagnostic'
      path: '/diagnostic'
      fullPath: '/diagnostic'
      preLoaderRoute: typeof AuthenticatedDiagnosticRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/topics/': {
      id: '/_authenticated/topics/'
      path: '/topics'
      fullPath: '/topics/'
      preLoaderRoute: typeof AuthenticatedTopicsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tools/': {
      id: '/_authenticated/tools/'
      path: '/tools'
      fullPath: '/tools/'
      preLoaderRoute: typeof AuthenticatedToolsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/theory/': {
      id: '/_authenticated/theory/'
      path: '/theory'
      fullPath: '/theory/'
      preLoaderRoute: typeof AuthenticatedTheoryIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/study/': {
      id: '/_authenticated/study/'
      path: '/study'
      fullPath: '/study/'
      preLoaderRoute: typeof AuthenticatedStudyIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/topics/$slug': {
      id: '/_authenticated/topics/$slug'
      path: '/topics/$slug'
      fullPath: '/topics/$slug'
      preLoaderRoute: typeof AuthenticatedTopicsSlugRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tools/functions': {
      id: '/_authenticated/tools/functions'
      path: '/tools/functions'
      fullPath: '/tools/functions'
      preLoaderRoute: typeof AuthenticatedToolsFunctionsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tools/calculator': {
      id: '/_authenticated/tools/calculator'
      path: '/tools/calculator'
      fullPath: '/tools/calculator'
      preLoaderRoute: typeof AuthenticatedToolsCalculatorRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/theory/$slug': {
      id: '/_authenticated/theory/$slug'
      path: '/theory/$slug'
      fullPath: '/theory/$slug'
      preLoaderRoute: typeof AuthenticatedTheorySlugRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/study/$id': {
      id: '/_authenticated/study/$id'
      path: '/study/$id'
      fullPath: '/study/$id'
      preLoaderRoute: typeof AuthenticatedStudyIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/materials/$id': {
      id: '/_authenticated/materials/$id'
      path: '/materials/$id'
      fullPath: '/materials/$id'
      preLoaderRoute: typeof AuthenticatedMaterialsIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/reports': {
      id: '/_authenticated/admin/reports'
      path: '/admin/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AuthenticatedAdminReportsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/analytics': {
      id: '/_authenticated/admin/analytics'
      path: '/admin/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AuthenticatedAdminAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDiagnosticRoute: typeof AuthenticatedDiagnosticRoute
  AuthenticatedExamRoute: typeof AuthenticatedExamRoute
  AuthenticatedExploreRoute: typeof AuthenticatedExploreRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedProgressRoute: typeof AuthenticatedProgressRoute
  AuthenticatedReviewRoute: typeof AuthenticatedReviewRoute
  AuthenticatedAdminAnalyticsRoute: typeof AuthenticatedAdminAnalyticsRoute
  AuthenticatedAdminReportsRoute: typeof AuthenticatedAdminReportsRoute
  AuthenticatedMaterialsIdRoute: typeof AuthenticatedMaterialsIdRoute
  AuthenticatedStudyIdRoute: typeof AuthenticatedStudyIdRoute
  AuthenticatedTheorySlugRoute: typeof AuthenticatedTheorySlugRoute
  AuthenticatedToolsCalculatorRoute: typeof AuthenticatedToolsCalculatorRoute
  AuthenticatedToolsFunctionsRoute: typeof AuthenticatedToolsFunctionsRoute
  AuthenticatedTopicsSlugRoute: typeof AuthenticatedTopicsSlugRoute
  AuthenticatedStudyIndexRoute: typeof AuthenticatedStudyIndexRoute
  AuthenticatedTheoryIndexRoute: typeof AuthenticatedTheoryIndexRoute
  AuthenticatedToolsIndexRoute: typeof AuthenticatedToolsIndexRoute
  AuthenticatedTopicsIndexRoute: typeof AuthenticatedTopicsIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDiagnosticRoute: AuthenticatedDiagnosticRoute,
  AuthenticatedExamRoute: AuthenticatedExamRoute,
  AuthenticatedExploreRoute: AuthenticatedExploreRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedProgressRoute: AuthenticatedProgressRoute,
  AuthenticatedReviewRoute: AuthenticatedReviewRoute,
  AuthenticatedAdminAnalyticsRoute: AuthenticatedAdminAnalyticsRoute,
  AuthenticatedAdminReportsRoute: AuthenticatedAdminReportsRoute,
  AuthenticatedMaterialsIdRoute: AuthenticatedMaterialsIdRoute,
  AuthenticatedStudyIdRoute: AuthenticatedStudyIdRoute,
  AuthenticatedTheorySlugRoute: AuthenticatedTheorySlugRoute,
  AuthenticatedToolsCalculatorRoute: AuthenticatedToolsCalculatorRoute,
  AuthenticatedToolsFunctionsRoute: AuthenticatedToolsFunctionsRoute,
  AuthenticatedTopicsSlugRoute: AuthenticatedTopicsSlugRoute,
  AuthenticatedStudyIndexRoute: AuthenticatedStudyIndexRoute,
  AuthenticatedTheoryIndexRoute: AuthenticatedTheoryIndexRoute,
  AuthenticatedToolsIndexRoute: AuthenticatedToolsIndexRoute,
  AuthenticatedTopicsIndexRoute: AuthenticatedTopicsIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
